🍕 [feature-tabTwoScreen] : 캘린더 로직 추가, 미팅 룸 스크린 로직 추가, 로그인 스크린생성,
Come-On-App/Come-On-Frontend pull request #26
Opened 2023-01-13 13:53 UTC by bananana0118

## 🍞 Motivation

- dummyData를 생성해서 임시로 로직을 추가하였습니다. 
- dummyData용 임시타입을 선언해서 생성했습니다. (추후 변경될 수 있습니다.)

## 🍪 features

- 캘린더 로직 추가
- 미팅 룸 스크린 로직 추가
- 로그인 스크린생성

## 🔑 key Changes 
- 캘린더 타입을 지정할 수 있습니다. (DEFAULT | PERIOD)

<br>
<br>
<hr>

2023-01-13 16:14 UTC, jeongbaebang requested changes
예정님 작업하시느라 너무 고생하셨어요 

전체적으로 컴포넌트를 좀 더 세분화해서 구분하면 작업할 때 더 좋을 것 같습니다!
또한 매직 넘버/리터럴보단 지양하는게 좋겠습니다~

2023-01-14 03:14 UTC, bananana0118 commented on components/Calendar/Calendar.tsx
> +  const [markedDate, setMarkedDate] = useState({});
아녀 ..

2023-01-14 03:20 UTC, bananana0118 commented on components/Calendar/CustomCalendarTheme.tsx
> +export const DayTheme = createTheme({
넵

2023-01-14 03:44 UTC, bananana0118 commented on components/inputComponents/InputForm.tsx
> +      <KeyboardAvoidingView behavior="padding" style={styles.container}>
깔끔 그 자체로 분리했어요

2023-01-14 03:48 UTC, bananana0118 commented on components/member/MemberBox.tsx
> +  const filtered = filterStaff();
오 베리 굿 피드백

2023-01-14 04:37 UTC, bananana0118 commented on components/Calendar/Calendar.tsx
> +function CalendarHeader(date: XDate): ReactNode {
라이브러리가 props로  xDate로 주고 xDate의 함수를 활용하기 위해 xDate를 사용했습니다.
또 라이브러리의 renderHeader가 ReactNode를 인자로 받고있어서 ReactNode를 명시해 주었습니다.

다른곳에선 사용하고 있지 않습니다

2023-01-14 04:44 UTC, bananana0118 commented on components/Calendar/Calendar.tsx
> +          backgroundColor: `rgba(51,127,254, ${item.userCount / userCount!})`,
현재 캘린더는 두가지 타입으로 나뉩니다. 
Default타입은 유저 모임을 생성한 후 미팅룸에서 보여주는 캘린더로, 모임생성 이후 이므로 넘겨줄 데이터가 있습니다. 
Period타입은 유저모임 생성전 단계에서 출력해줄 빈 캘린더입니다. 
유저가 값을 선택해야 하기 때문에 초반에 데이터를 받고있지 않습니다.

현재 캘린더는 하나의 컴포넌트가 두가지 타입을 받아야하기 때문에 data의 타입이 meetingResponse | undefined
인 상황입니다.

그래서 userCount에서 undefined 일 수 있다는 경고가 떳고 이를 제거하기위해 ! 를 사용했습니다.

타입을 캘린더 컴포넌트를 그냥 컴포넌트를 두개 만드는게 나을까요 🤔?

2023-01-14 05:11 UTC, jeongbaebang commented on components/Calendar/Calendar.tsx
> +          backgroundColor: `rgba(51,127,254, ${item.userCount / userCount!})`,
undefined 일 수 있다는 경고를 제거하기 위해서! 연산자를 사용한다는 게 어떤 의미인지 잘 모르겠습니다.
userCount! 가 평가된다면 어떤 값이 평가되나요?

2023-01-14 05:12 UTC, bananana0118 commented on components/Calendar/Calendar.tsx
> +              renderHeader={date => CalendarHeader(date!)}
위에 캘린더와 같은 이유입니다.

2023-01-14 05:21 UTC, bananana0118 commented on components/Calendar/Calendar.tsx
> +          backgroundColor: `rgba(51,127,254, ${item.userCount / userCount!})`,
어라라 왜 안나지 분명났었는데
![image](https://user-images.githubusercontent.com/28006318/212457250-0d8e3e45-7283-498b-9a1e-fbc55bad112b.png)
위와 같은 에러가 났었는데 혼동했나봐요 ㅎ ... ㅎ

2023-01-17 10:11 UTC, bananana0118 commented on components/Calendar/Calendar.tsx
> +  strMonth = month < 10 ? `0${month}` : String(month);
현재는 다른 방식으로 구현했는데 다음 최적화때 적용해 보겠습니다 !

2023-01-17 10:12 UTC, bananana0118 commented on components/Calendar/Calendar.tsx
> +  const onPressDayHandlerPeriod = (date: DateData) => {
넴

2023-01-17 10:57 UTC, jeongbaebang approved these changes

2023-01-17 10:57 UTC, merged