🍕 [feature-tabTwoScreen] : 로그인 로직 추가, 소셜로그인 버튼 생성
Come-On-App/Come-On-Frontend pull request #49
Opened 2023-02-01 15:48 UTC by bananana0118

## 🍞 Motivation
- 로그인 로직을 추가했습니다. 
- 소셜로그인이 가능해집니다.
- apis.getUser에 정의된 getUser를 사용시 유저의 정보를 가져올 수 있습니다.

## 🍪 features

- 소셜로그인 버튼을 추가했습니다. (구글로그인, 카카오로그인)
- 로그인 로직을 추가했습니다.
-- 유저정보를 불러온 후, 에러코드를 이용해 액세스 토큰 만료 시 리프레시 토큰을 재발급합니다.
- 로그인 관련 타입이 추가됐습니다.

## 🔑 key Changes 
- index.tsx 부분이 expo 권장 login flow로 바뀌었으니 놀라지 마세요🤗

<br>
<br>
<hr>

2023-02-04 05:19 UTC, jeongbaebang requested changes

2023-02-04 05:19 UTC, jeongbaebang commented on utils/auth.tsx
> +export function Auth() {
네이밍만 추측해봤을땐 컴포넌트를 봔환하는 함수 같습니다.
다른 네이밍을 사용해주세요

2023-02-04 05:19 UTC, jeongbaebang commented on utils/auth.tsx
> +export const isAuth = () => {
isAuth, Auht 작업하는 로직 내용이 비슷해 보이네요.
하나로 만들어서 사용하는 게 좋아 보입니다.

컴포넌트 내부에서도 사용하는 로직이라면 커스텀 훅을 고려하면 좋을 것 같습니다.

2023-02-05 02:03 UTC, bananana0118 commented on api.ts
> +const TOKEN = async () => {
넵

2023-02-05 02:04 UTC, bananana0118 commented on api.ts
> +    if (res) {
그렇네요!

2023-02-05 02:12 UTC, bananana0118 commented on api.ts
> +  postRefreshToken: async () => {
넵

2023-02-05 02:41 UTC, bananana0118 commented on api.ts
> +
코드가 훨씬 깔끔해졌고 재사용하기 쉬워진것 같아요! 감사합니당 많이 배웠어요: )

저는 코드가 길어지는게 싫어서 전부 async await으로 쓰는 편이였는데, 이번에 작업하면서 에러핸들링 할 땐 catch, then으로 체이닝하는게 굉장히 편하다고 느꼈어요. 습관적으로라도 체이닝으로 에러핸들링을 하는것도 좋을 것 같구요.
그래서 내부적으로 복잡한 로직을 처리할 땐 .then 메소드 체이닝이 좋은 것 같다는 것에 동의합니다~
에러핸들링이 절대적으로 편하더라구요!

개인적으로 코드가 가로는 짧고 세로는 길게 끊기지 않고 늘어지는 구조를 좋아하지 않기때문에
에러핸들링이 크게 중요하지 않으면 내부적으로도 간단하게 처리할땐 async await을 사용해요

정배님 말 듣고보니 호출은 async/await으로  처리하고 내부는 체이닝하는걸로 스스로 약속하는것도 좋은데요?
저도 다음에 그런식으로 사용해봐야겠어요!

2023-02-05 08:16 UTC, bananana0118 commented on components/Calendar/Calendar.tsx
>        </View>
제 리팩토링한코드 너무 아름다워서 놀라지 마세요

2023-02-05 08:17 UTC, bananana0118 commented on navigation/index.tsx
> +  apis.getUser();
넵

2023-02-05 08:20 UTC, bananana0118 commented on utils/auth.tsx
> +export function Auth() {
넵

2023-02-05 08:43 UTC, bananana0118 commented on utils/auth.tsx
> +export const isAuth = () => {
넵 수정했습니다.

2023-02-05 08:43 UTC, bananana0118 commented on components/Calendar/Calendar.tsx
> +  const onPressDayHandlerPeriod = useCallback(
수정했습니다

2023-02-05 09:31 UTC, bananana0118 commented on api.ts
> +      return api
수정했습니다.

2023-02-05 16:12 UTC, jeongbaebang commented on api.ts
> +
async/awiat 키워드를 사용하는 이유도 결국은 가독성을 높이기 위해서 사용되는 키워드라는 점에서
예정님 말씀대로 내부에서 적절하게 async await 처리를 하는 것도 좋다고 생각됩니다.

아래 코드는 제가 만들 유틸 함수인데 Promise의 then 메서드 체이닝을 좀 더 간소하게 사용하기 위해서 만들어봤어요.
프로미스로 값을 시작해서 .then 메소드 체이닝이 많은 경우에서 사용하면 어떨까요?
내부 함수는 async/awiat를 포함한 비동기 함수를사용해도 무방하고, 일반 함수를 사용해도 문제가 없게 설계했습니다.

```ts
promiseFlow(async () => api(), [fn1, fn2, fn3, fn4...]);
```

```ts
export function promiseFlow<T, R>(
  promiseFn: () => Promise<T>,
  callbackFns: ((value: any) => any)[],
): Promise<R> {
  const [ZERO, ONE] = [0, 1];
  const fns = [...callbackFns];
  const { length } = fns;

  if (length === ONE) {
    return promiseFn().then(fns[ZERO]);
  }

  function recursive(promise: Promise<T>, currentIndex = ZERO): Promise<any> {
    if (currentIndex === length) {
      return promise;
    }

    const then = promise.then(fns[currentIndex]);

    return recursive(then, currentIndex + ONE);
  }

  return recursive(promiseFn());
}
```

2023-02-06 04:53 UTC, jeongbaebang approved these changes

2023-02-06 04:54 UTC, merged