🍕 [Feature] : 리스트, 마이페이지, API 연동 작업, 웹소켓
Come-On-App/Come-On-Frontend pull request #98
Opened 2023-03-12 10:50 UTC by jeongbaebang

## 🍞 Motivation

- 

## 🍪 features
1. 새로운 패키지 추가
2. React-query native 설정
3. queryClient 설정 변경
4. 모임 장소 API  업데이트
5. 멤버 API 업데이트
6. 모임 API 업데이트
7. redux slice 추가 & 속성 변경
8. 입장 코드 컴포넌트 리팩토링
9. 로고 컴포넌트 메모이제이션 적용
10. 불필요한 파일 삭제 (파일 이동)
11. 일부 컴포넌트 리팩토링
12. 모임 상세 레이아웃 컴포넌트 추가
13. 모임 카드 컴포넌트 리팩토링
14. 마이페이지 컴포넌트 리팩토링
15. 장소 카드 컴포넌트 리팩토링
16. 장소 선택 컴포넌트 리팩토링
17. redux slice 추가
18. redux 장소 전역 속성 수정
19. useCurrentLocation 커스텀 훅 추가
20. useSubscribe 커스텀 훅 추가
21. useWebSocket 커스텀 훅 추가
22. useAppState 커스텀 훅 추가
23. usePlaceLock 커스텀 훅 추가
24. useOnlineManager 커스텀 훅 추가
25. useRefreshBy 커스텀 훅 추가
26. useRefreshOnFocus 커스텀 훅 추가
27. react-query 커스텀 훅 추가
28. bottomTap 탭 컴포넌트 리팩토링
29. 모임 디테일 컴포넌트 리팩토링
30. 장소 선택/검색 컴포넌트 리팩토링
31. 타입 파일 재작성
32. log 유틸 함수 추가
33. alert 유틸 함수 수정
34. fn 유틸 함수 추가
35. 네비게이션 로직 수정 & 웹소켓 연결
36. BadgedAvatar 메모이제이션 적용

## 🔑 key Changes 
- 파일 위치를 변경하였습니다.
- 일부 파일 네이밍 & 함수 네이밍이 수정되었습니다.
- 웹 소켓을 연결하였습니다.
- 웹 소켓을 연결하면서 나오는 여러 문제를 일부 해결하였습니다.
- 일부 컴포넌트 렌더링 최적화 작업을 진행하였습니다.

<br>
<br>
<hr>

2023-03-13 14:17 UTC, bananana0118 requested changes

2023-03-13 14:17 UTC, bananana0118 commented on src/components/meetingCard/CardTop.tsx
> +  );
사실 info.people 같은 경우를 일일이 디스트럭팅 해주는게 좋을지 아닐지 잘 모르겠어요
const { people, isDecided } = info 이런식의 사용이 권장되기는 하는 것 같은데 저도 잘 안지킬때가 많거든요
어떻게 생각하시는지 의견이 궁금합니당

2023-03-13 14:17 UTC, bananana0118 commented on App.tsx
> +
웹소켓 로직이 궁금한데 다음에 알려주세용!

2023-03-13 14:17 UTC, bananana0118 commented on src/hooks/useSubscribe.ts
> +
성능 최적화 꼼꼼히 하신게 보여요

2023-03-13 14:17 UTC, bananana0118 requested changes
고생하셨습니당

2023-03-14 06:28 UTC, jeongbaebang commented on src/screens/place/Search.tsx
소프트 키보드가 포커스 되어서 사용자에게 키보드를 활성화하는 시간에 대해서 딜레이를 주는 목적으로 작성했어요

2023-03-14 06:33 UTC, jeongbaebang commented on src/screens/meeting/detail/date.tsx
> +      }}
해당 부분은 모임 디테일에서 모임 기간에 관련된 부분을 만든 것인데 임시로 화면 영역을 주기 위해서 작성된 거예요
제가 주석으로 따로 명시를 하지 않았네요

2023-03-14 06:33 UTC, jeongbaebang commented on src/screens/meeting/detail/Member.tsx
> +      <BoldFont>모임 멤버</BoldFont>
위 코멘트와 같은 내용입니다.

2023-03-14 06:37 UTC, jeongbaebang commented on src/hooks/query/useAppState.ts
> +    return () => {
해당 리스너의 역할은 react-query 라이브러리를 사용하면서 웹에서는 불필요한 작업이지만 (기본으로 설정됨) 앱과 같은 플랫폼에서 react-query가 화면이 전환된다는것을 감지하지 못하기 때문에 감지할수있도록 도와주는 역할을 합니다.

기본적으로 react-query 라이브러리를 사용하면 특정 스크린으로 화면이 전환되는 경우 혹은 재포커스가 되는 경우에는 네트워크에 재요청을 시도합니다!

2023-03-14 06:41 UTC, jeongbaebang commented on src/hooks/useMeetings.ts
해당 부분은 제가 파일을 착각해서 실수로 다른 로직으로 덮었다가 다시 복구시켰어요
머지할때 다시 얘기드리겠습니다.

2023-03-14 06:42 UTC, jeongbaebang commented on src/hooks/query/usePlaceMutation.ts
> +} from '@api/meeting/places';
API에서 GET /api/v2/meetings 이런 형태로 v2 API라는 것을 명시하기 위해서 뒤에 넘버링을 붙였습니다

2023-03-14 06:49 UTC, jeongbaebang commented on src/hooks/useWebSocket.ts
> +  useLayoutEffect(() => {
원래 렌더링 결과가 화면에 그려지기 전에 실행을 하기 위해서 useLayoutEffect을 사용했지만
여러 가지 자료조사를 해보니 useLayoutEffect는 DOM을 조작할 때만 사용하는 것이 좋다고 나와있네요
하지만 웹소켓 이벤트를 수신하는 부분에서 useEffect를 사용하여 처리하는 게 좋다는 거고,
소켓 연결 자체를 하는 로직에서는 useLayoutEffect가 오히려 낫다고 생각되는데 어떻게 작성해야 하는지 고민이 되네요

2023-03-14 06:55 UTC, jeongbaebang commented on src/hooks/useWebSocket.ts
> +  useLayoutEffect(() => {
추가로 자료조사를 해본결과
useLayoutEffect는 DOM 조작 등의 작업을 수행할 때 사용하는 것이 좋다고 합니다
웹소켓을 연결하는 것은 일반적으로 DOM과 관련이 없으며, 컴포넌트가 렌더링될 때마다 다시 실행될 필요가 없기 때문이죠
웹소켓을 연결하는 로직은 보통 컴포넌트가 마운트될 때 한 번만 실행되도록 구현합니다. 
따라서, 웹소켓을 연결하는 로직은 useEffect 내부에서 작성하는 것이 적합합니다.
또한, useLayoutEffect는 브라우저가 페이지를 그리기 전에 실행되기 때문에, 웹소켓 연결 과정에서 불필요한 로딩 시간이 발생할 수 있습니다. 따라서, 웹소켓 연결 로직은 일반적으로 useEffect를 사용하여 컴포넌트가 마운트되거나 특정 props나 state가 업데이트될 때마다 실행되도록 구현하는 것이 좋습니다. 따라서 useEffect형태로 바꾸기로 결정했습니다.

2023-03-14 07:03 UTC, jeongbaebang commented on src/components/meetingCard/CardTop.tsx
> +  );
저도 예전에 작업할 때는 무조건적으로 특정 문법이 맞다 (권장된다)라고 생각했지만,
코드의 상황, 코드의 길이 등 여러 가지를 두고 괜찮다고 하는 방식으로 작성하고 있어요
결국 어떻게 작성해야 괜찮은지 여러 가지 시도를 해보는 중입니다.
특정 객체의 참조가 많은 경우에는 구조 분해 할당으로 작업하고 참조가 적은 경우에는 객체를 바로 참조하는 형태로도 작성하고 있어요
추가로 코드의 문맥상에 어울린다면 구조 분해 할당보다 오히려 가독성이 높다고 생각됩니다.
```ts
const emailInfo = {
  name: 'rich',
};
const user = {
  name: 'bang',
  age: 20,
};
const { name, age } = user;

console.log(name); // 코드가 많다면 어디서 파생된 이름인지 파악하는데 시간이 걸립니다.
console.log(user.name); // 사용자 객체에서 참조된 이름이라는 것을 파악하는데 빠릅니다.
```

2023-03-14 07:06 UTC, jeongbaebang commented on src/hooks/useSubscribe.ts
> +
위 코드에서 useMemo를 사용한 이유는 useEffect 훅에서 해당 함수를 참조하고 있기 때문입니다.
만약에 메모제이션을 처리하지 않는다면 종속성 배열의 참조로 인해서 useEffect 훅이 의도하지 않게 다시 실행되는 것을 막기 위해서 작성했습니다.

2023-03-14 12:26 UTC, bananana0118 commented on src/components/meetingCard/CardTop.tsx
> +  );
좋습니다.

2023-03-14 14:01 UTC, bananana0118 approved these changes

2023-03-14 14:02 UTC, merged